apiVersion: v1
kind: ConfigMap
metadata:
  name: lam-config
  namespace: lam-system
data:
  LAM_LOG_LEVEL: "INFO"
  LAM_DATA_DIR: "/data/lam"
  PYTHONUNBUFFERED: "1"
  # Lightfoot & Donte Constants
  LIGHTFOOT_CONSTANT: "0.16905"
  DONTE_CONSTANT: "149.9992314000"
